Fix conda build

diff --git a/.github/workflows/pack-debian.yml b/.github/workflows/pack-debian.yml
--- a/.github/workflows/pack-debian.yml
+++ b/.github/workflows/pack-debian.yml
@@ -84,23 +84,20 @@ jobs:
           echo "ID=$ID" >> "$GITHUB_ENV"
           echo "VERSION_CODENAME=$VERSION_CODENAME" >> "$GITHUB_ENV"
           echo "MPI_IMPLEMENTATION=${{ inputs.mpi_implementation || 'openmpi' }}" >> "$GITHUB_ENV"
-
+      - name: Install curl
+        run: |
+          apt-get update
+          apt-get install -y curl
+      - name: Download and install Khiops core
+        run: |
+          curl -L https://github.com/KhiopsML/khiops/releases/download/10.2.3/khiops-core-${{ env.MPI_IMPLEMENTATION }}_10.2.3-1-${{ env.VERSION_CODENAME }}.amd64.deb --output ./artifacts/khiops-core.deb
+          dpkg -i ./artifacts/khiops-core* || true
+          apt-get -f install -y
       - name: Download artifacts (driver package)
         uses: actions/download-artifact@v4
         with:
           name: deb-${{ env.ID }}-${{ env.VERSION_CODENAME }}
           path: artifacts
-      - name: Install Khiops core
-        run: |
-          apt-get update
-          apt-get install -y curl
-      - name: Download Khiops core
-        run: |
-          curl -L https://github.com/KhiopsML/khiops/releases/download/10.2.3/khiops-core-${{ env.MPI_IMPLEMENTATION }}_10.2.3-1-${{ env.VERSION_CODENAME }}.amd64.deb --output ./artifacts/khiops-core.deb
-      - name: Install Khiops core
-        run: |
-          dpkg -i ./artifacts/khiops-core* || true
-          apt-get -f install -y
       - name: Install driver
         run: dpkg -i ./artifacts/deb-*
       - name: Check Khiops core installation
@@ -111,3 +108,45 @@ jobs:
         uses: ./.github/actions/test-khiops-on-iris
         with:
           os-decription: ${{ env.ID }}-${{ env.VERSION_CODENAME }}
+
+  # Release is only executed on tags
+  release:
+    if: github.ref_type == 'tag'
+    # We release even if the tests fail (we delete from the release whatever fails manually)
+    needs: build
+    permissions:
+      contents: write
+    runs-on: ubuntu-latest
+    steps:
+      - name: Download package artifacts
+        uses: actions/download-artifact@v4
+        with:
+          # See the upload-artifact step in the build job for the explanation of this pattern
+          pattern: deb-*
+          merge-multiple: true
+      - name: Rename packages with tag version
+        run: |
+         # Renames the packge only if the source version differs from the tag
+         SOURCE_VERSION=$(./scripts/driver-version | sed 's/-/_/')
+         TAG_VERSION=$(echo "${{ github.ref_name }}" | sed 's/-/_/')
+         for PKG_FILE in *.deb
+         do
+           NEW_PKG_FILE=$(echo $PKG_FILE | sed "s/_${SOURCE_VERSION}-/_${TAG_VERSION}-/")
+           if [[ "$PKG_FILE" != "$NEW_PKG_FILE" ]]
+           then
+             echo "Renaming '$PKG_FILE' to '$NEW_PKG_FILE'"
+             mv $PKG_FILE $NEW_PKG_FILE
+           fi
+         done
+      - name: Upload packages to the release
+        uses: ncipollo/release-action@v1.14.0
+        with:
+          allowUpdates: true
+          artifacts: '*.deb'
+          body: |
+            **This release is for testing purposes only and there is no support for it.**
+            **Go to https://khiops.org to install the latest supported version.**
+          draft: false
+          makeLatest: false
+          prerelease: true
+          updateOnlyUnreleased: true
